Adding directory for joint imaging scripts
ACES-CMZ/reduction_ACES pull request #195
Opened 2022-08-03 15:09 UTC by d-l-walker

2022-08-03 17:10 UTC, keflavich commented
You don't need a copy of `default_tclean_commands.json` since that already exists elsewhere in the repository; I'd recommend removing that from this PR.

2022-08-03 17:51 UTC, keflavich requested changes
Don't track `.pyc` files, they are junk.

I suggest adopting some different python patters generally.  I gave a few examples.  These are mostly minor - no functionality change - but it's good practice to adopt "pythonic" norms.

I suggest changing path handling, though - there are some awkward hard-coded path assumptions that we should make more modular.

2022-08-03 17:51 UTC, keflavich commented on joint_deconvolution/joint_deconvolution_and_feather_auto.py
> +vis_all     = glob.glob(pth+'/'+region+'/twelve_m/spws/*.spw3') + glob.glob(pth+'/'+region+'/seven_m/spws/*.spw3')
general recommendation (python-wide): either do
```suggestion
vis_all     = glob.glob(os.path.join(pth, region, '/twelve_m/spws/*.spw3')) + glob.glob(os.path.join(region, '/seven_m/spws/*.spw3'))
```
or
`f'{pth}/{region}/twelve/...`

The former is more robust (it works on windows, for example), while the latter is easier to read

2022-08-03 17:51 UTC, keflavich commented on joint_deconvolution/joint_deconvolution_and_feather_auto.py
> +with open(f"./default_tclean_commands.json", "r") as fh:
if we don't have `default_tclean_commands.json` in the same directory, as I'm suggesting above, we should do something like what we do [elsewhere](https://github.com/ACES-CMZ/reduction_ACES/blob/158e54b4b2f9ca0900832e62755c4981cf977668/retrieval_scripts/run_pipeline.py#L45), i.e.:
```python
rootdir = os.getenv['ACES_ROOTDIR']
with open(f"{rootdir}/pipeline_scripts/default_tclean_commands.json", "r") as fh:
```

2022-08-03 17:51 UTC, keflavich commented on joint_deconvolution/joint_deconvolution_and_feather_auto.py
> +if os.path.isdir(region+'_12m_7m_SPW3_concat.ms')==False:
```suggestion
if not os.path.isdir(region+'_12m_7m_SPW3_concat.ms'):
```

`==False` is discouraged

2022-08-03 17:51 UTC, keflavich commented on joint_deconvolution/joint_deconvolution_and_feather_auto.py
> +if os.path.isdir(pth+'/'+region+'/clean_12m_7m/'+region+'_12m_7m_SPW3.clean.image')==False and os.path.isdir(pth+'/'+region+'/clean_12m_7m/'+region+'_12m_7m_TP.SPW3')==False:
```suggestion
if not os.path.isdir(pth+'/'+region+'/clean_12m_7m/'+region+'_12m_7m_SPW3.clean.image') and not os.path.isdir(pth+'/'+region+'/clean_12m_7m/'+region+'_12m_7m_TP.SPW3'):
```

2022-08-03 17:51 UTC, keflavich commented on joint_deconvolution/joint_deconvolution_and_feather_auto.py
> +if os.path.isdir(pth+'/'+region+'/clean_12m_7m/'+region+'_12m_7m_SPW3.clean.image')==True:
```suggestion
if os.path.isdir(pth+'/'+region+'/clean_12m_7m/'+region+'_12m_7m_SPW3.clean.image'):
```

2022-08-03 17:51 UTC, keflavich commented on joint_deconvolution/joint_deconvolution_and_feather_auto.py
> +    if os.path.isdir(tp_data+'.reframe')==True:
```suggestion
    if os.path.isdir(tp_data+'.reframe'):
```

2022-08-04 08:44 UTC, d-l-walker commented
Thanks Adam! 
Yeah, I was aware that the hard-coded path assumptions were not ideal. I should have had this in mind during my initial testing, but ended up just going with a local structure. When I get the time, I will try to restructure this so that it works in the general ACES structure.

And yeah, I forgot to remove the unnecessary files (.pyc, .json) before pushing this. Thanks for catching that.

2022-08-04 11:57 UTC, keflavich commented
Sounds good.   We can merge any time you want just to have the base code in the repository, or we can leave this PR open until you're ready to refactor the paths.

2022-08-05 10:11 UTC, d-l-walker commented
I'm happy for this to be merged as-is. Once it's in the main repo I'll just work from there when I get a chance to sort the paths out. I see that merging is blocked -- I think maybe you need to review the changes that were made based on your suggestions? If I'm wrong and I can do that myself, let me know!

2022-08-05 13:03 UTC, keflavich approved these changes

2022-08-05 13:03 UTC, merged